/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.desingcalculadora;

/**
 *
 * @author Usuario
 */
public class Calculadora extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    private String digito = "";

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jb_num1 = new javax.swing.JButton();
        jb_num2 = new javax.swing.JButton();
        jb_num3 = new javax.swing.JButton();
        jb_num4 = new javax.swing.JButton();
        jb_num5 = new javax.swing.JButton();
        jb_num6 = new javax.swing.JButton();
        jb_num7 = new javax.swing.JButton();
        jb_num8 = new javax.swing.JButton();
        jb_num9 = new javax.swing.JButton();
        jb_num0 = new javax.swing.JButton();
        jt_resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        jb_num1.setText("1");
        jb_num1.addActionListener(this::jb_num1ActionPerformed);

        jb_num2.setText("4");
        jb_num2.addActionListener(this::jb_num2ActionPerformed);

        jb_num3.setText("7");
        jb_num3.addActionListener(this::jb_num3ActionPerformed);

        jb_num4.setText("0");
        jb_num4.addActionListener(this::jb_num4ActionPerformed);

        jb_num5.setText("5");
        jb_num5.addActionListener(this::jb_num5ActionPerformed);

        jb_num6.setText("8");
        jb_num6.addActionListener(this::jb_num6ActionPerformed);

        jb_num7.setText("2");
        jb_num7.addActionListener(this::jb_num7ActionPerformed);

        jb_num8.setText("6");
        jb_num8.addActionListener(this::jb_num8ActionPerformed);

        jb_num9.setText("9");
        jb_num9.addActionListener(this::jb_num9ActionPerformed);

        jb_num0.setText("3");
        jb_num0.addActionListener(this::jb_num0ActionPerformed);

        jt_resultado.setEditable(false);
        jt_resultado.setBackground(new java.awt.Color(204, 204, 255));
        jt_resultado.setForeground(new java.awt.Color(204, 204, 255));
        jt_resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_num1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jb_num2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_num3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_num4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jb_num6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_num5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_num7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_num0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_num8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_num9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addComponent(jt_resultado)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_num1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jb_num0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_num7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_num2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jb_num5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_num8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_num3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_num6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_num9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jb_num4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num1ActionPerformed
        jt_resultado.setText(jt_resultado.getText() + digito); 
    }//GEN-LAST:event_jb_num1ActionPerformed

    private void jb_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num2ActionPerformed
        digito = jb_num2.getText();
    }//GEN-LAST:event_jb_num2ActionPerformed

    private void jb_num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num3ActionPerformed
        digito = jb_num3.getText();
    }//GEN-LAST:event_jb_num3ActionPerformed

    private void jb_num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num4ActionPerformed
        digito = jb_num4.getText();
    }//GEN-LAST:event_jb_num4ActionPerformed

    private void jb_num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num5ActionPerformed
        digito = jb_num5.getText();
    }//GEN-LAST:event_jb_num5ActionPerformed

    private void jb_num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num6ActionPerformed
        digito = jb_num6.getText();
    }//GEN-LAST:event_jb_num6ActionPerformed

    private void jb_num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num7ActionPerformed
        digito = jb_num7.getText();
    }//GEN-LAST:event_jb_num7ActionPerformed

    private void jb_num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num8ActionPerformed
        digito = jb_num8.getText();
    }//GEN-LAST:event_jb_num8ActionPerformed

    private void jb_num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num9ActionPerformed
        digito = jb_num9.getText();
    }//GEN-LAST:event_jb_num9ActionPerformed

    private void jb_num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_num0ActionPerformed
        digito = jb_num0.getText();
    }//GEN-LAST:event_jb_num0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_num0;
    private javax.swing.JButton jb_num1;
    private javax.swing.JButton jb_num2;
    private javax.swing.JButton jb_num3;
    private javax.swing.JButton jb_num4;
    private javax.swing.JButton jb_num5;
    private javax.swing.JButton jb_num6;
    private javax.swing.JButton jb_num7;
    private javax.swing.JButton jb_num8;
    private javax.swing.JButton jb_num9;
    private javax.swing.JTextField jt_resultado;
    // End of variables declaration//GEN-END:variables
}
